name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release test
    - name: Build CMake
      run: cmake --build tests --config Release
    - name: Run Tests
      run: ./mustache
